### ISSUE TITLE
Ansible deployment for Columbia

### ISSUE THREAD

**Issue by nickwilkinson** [artefactual/deploy-pub#51]
Ansible deployment -- any changes in https://github.com/artefactual/deploy-pub merged to master or changes required in https://github.com/artefactual-labs/ansible-archivematica-src merged to qa/1.7.x

**Comment by jrwdunham** [comment]
@nickwilkinson I am closing this in favour of referencing the specific PRs that are needed in deploy-pub and ansible-archivematica-src:

- [ansible-archivematica-src PR 171](https://github.com/artefactual-labs/ansible-archivematica-src/pull/171)
- [deploy-pub PR 52](https://github.com/artefactual/deploy-pub/pull/52)

These are now listed in the [meta AM issue 878](https://github.com/artefactual/archivematica/issues/878) instead of this issue.
